# Generated by Django 4.2.3 on 2023-07-18 14:51

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="title",
        ),
        migrations.AddField(
            model_name="menu",
            name="link",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StreamBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("link", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
