# Generated by Django 4.2.3 on 2023-07-18 16:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_remove_menu_slug_remove_menu_title_menu_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="link",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("link", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
