# Generated by Django 4.2.3 on 2023-07-18 16:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_menu_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="link",
        ),
        migrations.AddField(
            model_name="menu",
            name="menu_items",
            field=wagtail.fields.StreamField(
                [
                    (
                        "menu_items",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("link", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
