# Generated by Django 4.2.3 on 2023-07-18 16:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_remove_menu_link_menu_menu_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="menu_items",
            field=wagtail.fields.StreamField(
                [
                    (
                        "navigation_links",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("link", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
