# Generated by Django 4.2.3 on 2023-07-18 16:06

from django.db import migrations
import team.models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_remove_contentpage_body_alter_contentpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("subtitle", wagtail.blocks.CharBlock()),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "team_members",
                        wagtail.blocks.ListBlock(
                            wagtail.snippets.blocks.SnippetChooserBlock(
                                team.models.TeamMember
                            ),
                            icon="user",
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
