# Generated by Django 4.2.3 on 2023-07-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_title", models.CharField(max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("default_canonical_url", models.URLField(blank=True)),
                (
                    "default_robots_meta_tags",
                    models.CharField(blank=True, max_length=255),
                ),
            ],
            options={
                "verbose_name": "SEO Settings",
                "verbose_name_plural": "SEO Settings",
            },
        ),
    ]
