# Generated by Django 4.2.3 on 2023-07-18 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SEOSettings",
        ),
    ]
